# fly.toml app configuration file generated for restful-evaluation360 on 2025-01-11T21:45:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'restful-evaluation360'
primary_region = 'sin'

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
